apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: crates.crate.io
spec:
  group: crate.io
  names:
    kind: Crate
    listKind: CrateList
    plural: crates
    singular: crate
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
