apiVersion: apps/v1
kind: Deployment
metadata:
  name: crate-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: crate-operator
  template:
    metadata:
      labels:
        name: crate-operator
    spec:
      serviceAccountName: crate-operator
      containers:
        - name: crate-operator
          # Replace this with the built image name
          image: greegorey/crate-operator:0.0.1
          command:
          - crate-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "crate-operator"
